src/app/main/forms.py
"""

app/main/forms.py

written by: Oliver Cordes 2022-03-29
changed by: Oliver Cordes 2022-05-29

"""


from ast import Sub
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, \
                    SubmitField, TextAreaField, SelectField, SelectMultipleField, \
                    DateField, DateTimeField, RadioField 
#from wtforms_html5 import AutoAttrMeta

from wtforms.validators import ValidationError, DataRequired, Optional, Email, EqualTo, Length
from app.models import User, severities

from wtforms import widgets, SelectMultipleField

from flask_babel import lazy_gettext as _

import datetime


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class AddLabelForm(FlaskForm):
    name = StringField(_('Name'), validators=[DataRequired()])
    hint = StringField(_('Description'), validators=[DataRequired()])

    submit = SubmitField(_('Submit'))


class EditLabelForm(FlaskForm):
    name = StringField(_('Name'), validators=[DataRequired()])
    hint = StringField(_('Description'), validators=[DataRequired()])

    submit = SubmitField(_('Update'))


class DeleteLabelForm(FlaskForm):
    remove = SubmitField(_('Delete'))


class AddMessageForm(FlaskForm):
    title = StringField(_('Message title'), validators=[DataRequired()])
    valid = DateTimeField(_('Starting date/time'), format='%Y-%m-%d %H:%M')
    severity = RadioField(
        #'Severity', choices=[(1, 'Information'), (2, 'Feature'), (3,'Problem'), (4, 'Outage')], 
        _('Severity'), choices=[(1, severities[1]), (2, severities[2]), (3, severities[3]), (4, severities[4])], 
        coerce=int, default=1, validators=[DataRequired()])
    label = SelectField(_('Label'),coerce=int)
    send_email = BooleanField(_('Send email to ...'), default=False)
    email_body = TextAreaField(_('Email body'), validators=[Optional(), Length(max=200)])
    submit = SubmitField(_('Submit'))


    def validate_valid(self, valid):
        if valid.data is None:
            raise ValidationError(_('Date/Time is not in this format: YYYY-MM-DD HH:MM'))
        
        timediff = (valid.data - datetime.datetime.now()).total_seconds()
        if timediff <= 0:
            raise ValidationError(_('Date/Time must be in the future!'))



class EditMessageForm(FlaskForm):
    title = StringField(_('Message title'), validators=[DataRequired()])
    valid = DateTimeField(_('Starting date/time'), format='%Y-%m-%d %H:%M')
    severity = RadioField(
        #'Severity', choices=[(1, 'Information'), (2, 'Feature'), (3,'Problem'), (4, 'Outage')], 
        _('Severity'), choices=[(1, severities[1]), (2, severities[2]), (3, severities[3]), (4, severities[4])], 
        coerce=int, default=1, validators=[DataRequired()])
    label = SelectField(_('Label'), coerce=int)
    send_email = BooleanField(_('Send email to ...'), default=False)
    email_body = TextAreaField(_('Email body'), validators=[Optional(), Length(max=200)])
    submit = SubmitField(_('Update'))


    def validate_valid(self, valid):
        if valid.data is None:
            raise ValidationError(_('Date/Time is not in this format: YYYY-MM-DD HH:MM'))
        
        timediff = (valid.data - datetime.datetime.now()).total_seconds()
        if timediff <= 0:
            raise ValidationError(_('Date/Time must be in the future!'))



class DeleteMessageForm(FlaskForm):
    remove = SubmitField(_('Delete'))


# ------------------------------------------------------------
#
# email part

# helper class to mimik individual data fields
class _Emailfield(object):
    def __init__(self, data,gettext):
        self.data = data
        self.gettext = gettext


# wrapper around the email normal validator
class MultipleEmails(object):
    def __init__(self, delimiter=','):
        self._delimiter = delimiter


    def __call__(self, form, field):
        email_validator = Email()

        emails = field.data.split(self._delimiter)
        for email in emails:
            email_validator(form, _Emailfield(email,field.gettext))
    


class AddEmailForm(FlaskForm):
    name = StringField(_('Name of email group'), validators=[DataRequired()])
    email = StringField(_('Email address'), validators=[DataRequired(), MultipleEmails()])

    submit = SubmitField(_('Submit'))


class EditEmailForm(FlaskForm):
    name = StringField(_('Name of email group'), validators=[DataRequired()])
    email = StringField(_('Email address'), validators=[DataRequired(), MultipleEmails()])

    submit = SubmitField(_('Update'))


class DeleteEmailForm(FlaskForm):
    remove = SubmitField(_('Delete'))

src/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes, email

src/app/main/routes.py
# -*- coding: utf-8 -*-
"""

app/main/routes.py
~~~~~~~~~~~~~~~~~~

written by : Oliver Cordes 2022-03-29
changed by : Oliver Cordes 2022-05-29

"""

import os
from datetime import datetime, timedelta
from dateutil.relativedelta import *
import pkg_resources

from flask import current_app, g, request, render_template, url_for, flash,  \
    redirect, send_from_directory, jsonify, session, make_response
from flask_login import current_user, login_user, logout_user, login_required
from flask_babel import _, refresh
from werkzeug.urls import url_parse, url_unparse

from flask_paginate import Pagination, get_page_parameter

from app import db
from app.main import bp
from app.models import *
from app.main.forms import AddLabelForm, EditLabelForm, DeleteLabelForm, \
        AddMessageForm, EditMessageForm, DeleteMessageForm

from app.auth.admin import admin_required


APP_ROOT = os.path.dirname(os.path.abspath(__file__))


"""
before_request will be executed before any page will be
rendered
"""
@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/ping', methods=['GET'])
def ping():
    return 'pong'


"""
language selector
"""
@bp.route('/lang/<id>', methods=['GET'])
@login_required
def set_language(id):
    session['language'] = id
    return redirect(request.referrer)


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    installed_packages = [(d.project_name, d.version)
                          for d in pkg_resources.working_set][::-1]

    server_users = User.query.count()
    return render_template('index.html',
                            installed_packages=installed_packages,
                            server_users=server_users,
                                title='Dashboard'
                            )





@bp.route('/labels', methods=['GET', 'POST'])
@login_required
def show_labels():
    dform = DeleteLabelForm()

    if dform.validate_on_submit():
        selected_labels = request.form.getlist("remove_group")

        for id in selected_labels:
            label = MessageLabel.query.get(int(id))
            db.session.delete(label)
            db.session.commit()

    labels = MessageLabel.query.all()

    return render_template('main/labels.html',
                            labels=labels,
                            dform=dform,
                            title=_('Labels')
    )


@bp.route('/label/add', methods=['GET', 'POST'])
@login_required
def label_add():
    form = AddLabelForm()

    if form.validate_on_submit():
        label = MessageLabel(name=form.name.data, hint=form.hint.data)
        db.session.add(label)
        db.session.commit()

        return redirect(url_for('main.show_labels'))

    return render_template('main/label_edit.html',
                           title=_('Add label'),
                           edit=False,
                           nform=form,
                           )


@bp.route('/label/<id>/edit', methods=['GET', 'POST'])
@login_required
def label_edit(id):

    form = EditLabelForm()

    label = MessageLabel.query.get(int(id)) 

    if form.validate_on_submit():
        label.name = form.name.data
        label.hint = form.hint.data
        db.session.commit()

        return redirect(url_for('main.show_labels'))
    elif request.method == 'GET':
        form.name.data = label.name
        form.hint.data = label.hint

    return render_template('main/label_edit.html',
                            title=_('Edit label'),
                            edit=True,
                            nform=form
                            )


@bp.route('/label/<id>/delete')
@login_required
def label_delete(id):
    return redirect(url_for('main.show_labels'))



@bp.route('/messages', methods=['GET', 'POST'])
@login_required
def show_messages():
    # analyse the request
    search = False
    q = request.args.get('q')
    if q:
        search = True
    page     = request.args.get(get_page_parameter(), type=int, default=1)

    dform = DeleteMessageForm()
    labels = MessageLabel.query.all()

    if dform.validate_on_submit():
        print('remove pressed')
        # get a list of selected items
        selected_messages = request.form.getlist("remove_group")
        print(selected_messages)

        for id in selected_messages:
            msg = Message.query.get(int(id))
            db.session.delete(msg)
            db.session.commit()

        return redirect(url_for('main.show_messages'))

    max_messages = Message.query.count()

    pagination = Pagination(page=page, total=max_messages,
                            per_page=10,
                            css_framework='bootstrap4',
                            href=url_for('main.show_messages') +
                            '?page={}',
                            display_msg='(Displaying <b>{start}-{end}</b> of <b>{total}</b> Messages)',
                            search=search, record_name='whitelist_users')

    messages = Message.query.order_by(Message.valid).paginate(page, pagination.per_page, error_out=False).items

    return render_template('main/messages.html',
                            title=_('Messages'),
                            dform=dform,
                            pagination=pagination,
                            messages=messages,
                            labels=labels
                           )


@bp.route('/message/add', methods=['GET','POST'])
@login_required
def message_add():
    form = AddMessageForm()

    labels = MessageLabel.query.all()
    form.label.choices = [(l.id, l.name) for l in labels]

    if form.validate_on_submit():

        msg = Message(title=form.title.data)
        msg.valid = form.valid.data
        msg.severity = form.severity.data
        msg.label = form.label.data

        db.session.add(msg)
        db.session.commit()

        return redirect(url_for('main.show_messages'))

    
    return render_template('main/message_edit.html',
                           title=_('Add message'),
                           edit=False,
                           nform=form,
                           )


@bp.route('/message/<id>/edit', methods=['GET','POST'])
@login_required
def message_edit(id):
    form = EditMessageForm()

    labels = MessageLabel.query.all()
    form.label.choices = [(l.id, l.name) for l in labels]

    msg = Message.query.get(int(id))

    if form.validate_on_submit():
        msg.title = form.title.data 
        msg.valid = form.valid.data
        msg.severity = form.severity.data
        msg.label = form.label.data
        msg.send_email = form.send_email.data
        msg.email_body = form.email_body.data
        
        db.session.commit()

        return redirect(url_for('main.show_messages'))

    form.title.data      = msg.title
    form.valid.data      = msg.valid
    form.severity.data   = msg.severity
    form.label.data      = msg.label
    form.send_email.data = msg.send_email
    form.email_body.data = msg.email_body
    
    return render_template('main/message_edit.html',
                           title=_('Edit message'),
                           edit=True,
                           nform=form,
                           )


@bp.route('/message/<id>/delete')
@login_required
def message_delete(id):
    msg = Message.query.get(int(id))

    db.session.delete(msg)
    db.session.commit()

    return redirect(url_for('main.show_messages'))

src/app/templates/main/email_edit.html
{% extends "email_base.html" %}


{% block app_content %}

<div class="card">
    <div class="card-header">
        {% if edit %}
        <h5>Edit an email group</h5>
        {% else %}
        <h5>Add an email group</h5>
        {% endif %}
    </div>
    <div class="card-body">
        <form id="labelform" class="form-horizontal mb-2" role="form" method="post" action="">
            {{nform.hidden_tag()}}
            <div class="form-floating mb-2">
                {% if nform.name.errors|length > 0 %}
                {{nform.name(id="name", class_="form-control is-invalid", placeholder="{{nform.name.label}}" ) }}
                <label for="name">
                    {% for error in nform.name.errors %}
                    {{error}}
                    {% endfor %}
                </label>
                {% else %}
                {{nform.name(id="name", class_="form-control", placeholder="{{nform.name.label}}" ) }}
                <label for="name">{{nform.name.label}}</label>
                {% endif %}
            </div>
            <div class="form-floating mb-2">
                {% if nform.email.errors|length >0 %}
                {{nform.email(id="email", class_="form-control is-invalid", placeholder="{{nform.email.label}}" ) }}
                <label for="email">
                    {% for error in nform.email.errors %}
                    {{error}}
                    {% endfor %}
                </label>
                {% else %}
                {{nform.email(id="email", class_="form-control", placeholder="{{nform.email.label}}" ) }}
                <label for="email">{{nform.email.label}}</label>
                {% endif %}
            </div>
            {{ nform.submit(class_="btn btn-primary") }}
        </form>
    </div>
</div>


{% endblock %}

src/app/templates/main/emails.html
{% extends "email_base.html" %}


{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='pagination.css')}}">
{% endblock %}

{% block app_content %}

{% from 'bootstrap5/utils.html' import render_icon %}

<div class="card">
    <div class="card-header">
        <h5>List of available email groups</h5>
    </div>
    <div class="card-body">
        <form id="rolesformdelete" class="form-horizontal mb-5" role="form" method="post" action="">
            {{dform.hidden_tag()}}
            <div class="table-responsive col-lg-9 col-sm-12">
                <table class="table table-sm table-bordered">
                    <thead>
                        <td></td>
                        <td>ID</td>
                        <td>Group name</td>
                        <td>Email address</td>
                        <td>Time stamp</td>
                        <td></td>
                    </thead>
                    {% for email_address in email_addresses %}
                    <tr>
                        <td>
                            <label>
                                <input type="checkbox" name="remove_group" value="{{email_address.id}}">
                            </label>
                        </td>
                        <td>{{email_address.id}}</td>
                        <td>{{email_address.name}}</td>
                        <td>{{email_address.emails}}</td>
                        <td>{{email_address.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}</td>
                        <td>
                            <a class="action-icon text-decoration-none"
                                href="{{url_for('main.email_edit', id=email_address.id)}}">

                            {{ render_icon('pencil-fill') }}
                            </a>
                            <a class="action-icon text-decoration-none" 
                                href="{{url_for('main.email_delete', id=email_address.id)}}"
                                onclick="return (ask_for_deletion())">
                            
                                {{ render_icon('trash-fill') }}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            {{ dform.remove(onclick="return (ask_for_deletion())", class_="btn btn-danger") }}
        </form>
    </div>
</div>


{% endblock %}

src/app/templates/main/label_edit.html
{% extends "label_base.html" %}

{% block styles %}
{{super()}}

<link rel="stylesheet" href="{{url_for('static', filename='bootstrap-datetimepicker.min.css')}}">

{% endblock %}

{% block app_content %}

<div class="card">
    <div class="card-header">
        <h5>{{_('Label')}}</h5>
    </div>
    <div class="card-body">
        <form id="labelform" class="form-horizontal mb-2" role="form" method="post" action="">
            {{nform.hidden_tag()}}
            <div class="form-floating mb-2">
                {% if nform.name.errors|length > 0 %}
                {{nform.name(id="name", class_="form-control is-invalid", placeholder="Name of the label" ) }}
                <label for="name">
                    {% for error in nform.name.errors %}
                    {{error}}
                    {% endfor %}
                </label>
                {% else %}
                {{nform.name(id="name", class_="form-control", placeholder="Name of the label" ) }}
                <label for="name">{{nform.name.label()}}</label>
                {% endif %}
            </div>
            <div class="form-floating mb-2">
                {{nform.hint(id="hint", class_="form-control", placeholder="Description of the label" ) }}
                <label for="hint">{{nform.hint.label()}}</label>
            </div>
            {{ nform.submit(class_="btn btn-primary") }}
        </form>
    </div>
</div>


{% endblock %}


{% block scripts %}
{{super()}}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="{{url_for('static', filename='bootstrap-datetimepicker.min.js')}}"></script>

<!-- 
    https://www.jqueryscript.net/time-clock/Date-Time-Picker-Bootstrap-4.html
-->
<script>
    $(function () {
        $('#valid').datetimepicker({
            format: 'YYYY-MM-DD HH:mm'
        });
    });


</script>

{% endblock %}

src/app/templates/main/labels.html
{% extends "label_base.html" %}


{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='pagination.css')}}">
{% endblock %}

{% block app_content %}

{% from 'bootstrap5/utils.html' import render_icon %}

<div class="card">
    <div class="card-header">
        <h5>{{_('List of available labels')}}</h5>
    </div>
    <div class="card-body">
        <form id="rolesformdelete" class="form-horizontal mb-5" role="form" method="post" action="">
            {{dform.hidden_tag()}}
            <div class="table-responsive col-lg-9 col-sm-12">
                <table class="table  table-sm table-bordered">
                    <thead>
                        <td></td>
                        <td>ID</td>
                        <td>Name</td>
                        <td>{{_('Description')}}</td>
                        <td>{{_('Created')}}</td>
                        <td></td>
                    </thead>
                    {% for label in labels %}
                    <tr>
                        <td>
                            <label>
                                <input type="checkbox" name="remove_group" value="{{label.id}}">
                            </label>
                        </td>
                        <td>{{label.id}}</td>
                        <td>{{label.name}}</td>
                        <td>{{label.hint}}</td>
                        <td>{{label.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}</td>
                        <td>
                            <a class="action-icon text-decoration-none"
                                href="{{url_for('main.label_edit', id=label.id)}}">

                            {{ render_icon('pencil-fill') }}
                            </a>
                            <a class="action-icon text-decoration-none" href="{{url_for('main.label_delete', id=label.id)}}">
                            
                                {{ render_icon('trash-fill') }}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            {{ dform.remove(onclick="return (ask_for_deletion())", class_="btn btn-danger") }}
        </form>
    </div>
</div>


{% endblock %}

src/app/templates/main/message_add.html
{% extends "message_base.html" %}

{% block styles %}
{{super()}}

<link rel="stylesheet" href="{{url_for('static', filename='bootstrap-datetimepicker.min.css')}}">

{% endblock %}

{% block app_content %}

<div class="card">
    <div class="card-header">
        <h5>Add message</h5>
    </div>
    <div class="card-body">
        <form id="usersform" class="form-horizontal mb-5" role="form" method="post" action="">
            {{nform.hidden_tag()}}
            {% if nform.title.errors|length > 0 %}
            <div id="signupalert" class="alert alert-danger">
                {% for error in nform.title.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% endif %}
            <div class="input-group form-group row mb-2">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-comment"></i></span>
                </div>
                {{nform.title(id="title", class_="form-control", placeholder="message title" ) }}
            </div>
            {% if nform.valid.errors|length > 0 %}
            <div id="signupalert" class="alert alert-danger">
                {% for error in nform.valid.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% endif %}
            <div class="input-group form-group row mb-2">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                </div>
                {{nform.valid(id="valid", class_="datetime form-control" , placeholder="YYYY-MM-DD HH:MM") }}
            </div>

            <div class="input-group form-group row mb-2">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-info-circle"></i></span>
                </div>

                <!--{{nform.severity(id="valid", class_="list-inline") }}-->
                <div class="form-control list-inline">
                {% for i in nform.severity %}
                  {{i(class_="list-inline-item mt-2")}} {{i.label(class_="mt-2")}}
                {% endfor%}
                </div>
            </div>

            <div class="input-group form-group row mb-2">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-tag"></i></span>
                </div>
                {{nform.label(id="label", class_="form-control")}}
            </div>

            {{ nform.submit(class_="btn btn-primary") }}
        </form>
    </div>
</div>


{% endblock %}


{% block scripts %}
{{super()}}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="{{url_for('static', filename='bootstrap-datetimepicker.min.js')}}"></script>

<!-- 
    https://www.jqueryscript.net/time-clock/Date-Time-Picker-Bootstrap-4.html
-->
<script>
    $(function () {
        $('#valid').datetimepicker({
            format: 'YYYY-MM-DD HH:mm'
        });
    });


</script>

{% endblock %}

src/app/templates/main/messages.html
{% extends "message_base.html" %}


{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='pagination.css')}}">
{% endblock %}

{% block app_content %}

{% from 'bootstrap5/utils.html' import render_icon %}

<div class="card">
    <div class="card-header">
        <h5>{{_('List of available messages')}}</h5>
    </div>
    <div class="card-body">
        <form id="rolesformdelete" class="form-horizontal mb-5" role="form" method="post" action="">
            {{dform.hidden_tag()}}
            <div class="table-responsive">
                {{ pagination.links }}
                <table class="table table-sm table-bordered">
                    <thead>
                        <td></td>
                        <td>ID</td>
                        <td>{{_('Title')}}</td>
                        <td>{{_('Due in')}}</td>
                        <td>{{_('Due')}}</td>
                        <td>{{_('Severity')}}</td>
                        <td>{{_('Label')}}</td>
                        <td>{{_('Created')}}</td>
                        <td></td>
                    </thead>
                    {% for msg in messages %}
                    <tr>
                        <td>
                            <label>
                                <input type="checkbox" name="remove_group" value="{{msg.id}}">
                            </label>
                        </td>
                        <td>{{msg.id}}</td>
                        <td>{{msg.title}}</td>
                        <td style="background-color: {{msg.get_days_color()}}">{{msg.get_days()}}</td>
                        <td>{{msg.valid}}</td>
                        <!-- <td style="background-color: #eaffaf;" >{{msg.get_severity_name()}}</td>-->
                        <td style="background-color: {{msg.get_sev_color()}}">{{msg.get_severity_name()}}</td>
                        <td>{{msg.get_label_name()}}</td>
                        <td>{{msg.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}</td>
                        <td>
                            <a class="action-icon text-decoration-none" href="{{url_for('main.message_edit', id=msg.id)}}">
                                {{ render_icon('pencil-fill') }}
                            </a>
                            <a class="action-icon text-decoration-none" 
                                href="{{url_for('main.message_delete', id=msg.id)}}" 
                                onclick="return (ask_for_deletion_item('{{msg.title}}'))">
                                {{ render_icon('trash-fill') }}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                {{ pagination.info }}
                {{ pagination.links }}
            </div>
            {{ dform.remove(onclick="return (ask_for_deletion())", class_="btn btn-danger") }}
        </form>
    </div>
</div>

{% endblock %}